export enum PLATFORM {
  FACEBOOK = 'FACEBOOK',
  INSTAGRAM = 'INSTAGRAM',
  TWITTER = 'TWITTER',
  YOUTUBE = 'YOUTUBE',
}
export enum STATUS {
  INCREASE = 'INCREASE',
  DECREASE = 'DECREASE',
}

export enum TYPE {
  PAGE_VIEWS = 'PAGE_VIEWS',
  PROFILE_VIEWS = 'PROFILE_VIEWS',
  TOTAL_VIEWS = 'TOTAL_VIEWS',
  RETWEETS = 'RETWEETS',
  LIKES = 'LIKES',
}